---

- name: "Criando estrutura de diretorios em {{ home_dir }}/{{ root_env_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: 0775
    recurse: yes
  with_items:
    - "{{ home_dir }}/{{ root_env_dir }}/devops/ansible/inventories"
    - "{{ home_dir }}/{{ root_env_dir }}/devops/ansible/keys"
    - "{{ home_dir }}/{{ root_env_dir }}/devops/ansible/logs"
    - "{{ home_dir }}/{{ root_env_dir }}/devops/ansible/playbooks"
    - "{{ home_dir }}/{{ root_env_dir }}/devops/ansible/roles"
  become: true
  tags:
    - ansible
    - directory


- name: "Gerando o arquivo de configuração em /etc/ansible/ansible.cfg"
  shell: "ansible-config init > /etc/ansible/ansible.cfg"
  become: true
  tags:
    - ansible
    - config


- name: "Atualizando a propriedade roles_path em /etc/ansible/ansible.cfg"
  lineinfile:
    path: "/etc/ansible/ansible.cfg"
    regexp: "roles_path"
    line: "roles_path=/usr/share/ansible/roles:/etc/ansible/roles:{{ home_dir }}/{{ root_env_dir }}/devops/ansible/roles"
    backrefs: yes
    state: present
  become: true
  tags:
    - ansible
    - config


- name: "Atualizando a propriedade log_path em '/etc/ansible/ansible.cfg'"
  lineinfile:
    path: "/etc/ansible/ansible.cfg"
    regexp: "log_path"
    line: "log_path={{ home_dir }}/{{ root_env_dir }}/devops/ansible/logs/ansible.log"
    backrefs: yes
    state: present
  become: true
  tags:
    - ansible
    - config


- name: "Atualizando a propriedade timeout em '/etc/ansible/ansible.cfg'"
  lineinfile:
    path: "/etc/ansible/ansible.cfg"
    regexp: "timeout="
    line: "timeout={{ timeout_value }}"
    backrefs: yes
    state: present
  become: true
  tags:
    - ansible
    - config
