---

- name: "Instalando o pacote 'Ansible'"
  dnf:
   name: ansible
   state: present
  become: true
  tags:
   - ansible


- name: "Gerando o arquivo de configuração em /etc/ansible/ansible.cfg"
  shell: "ansible-config init > /etc/ansible/ansible.cfg"
  become: true
  tags:
    - ansible
    - config