---


- include_tasks: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution | lower }}.yml"
   - "{{ ansible_os_family | lower }}.yml"
   - "os_defaults.yml"
  tags: 
   - main


- name: Configurando o ambiente default do Ansible
  when: ansible_unsupported_os is not defined and root_env_dir is not defined
  include_tasks: "default_config.yml"
  tags: 
   - main

   
- name: Configurando o ambiente customizado do Ansible
  when: ansible_unsupported_os is not defined and root_env_dir is defined
  include_tasks: "custom_config.yml"
  tags: 
   - main