---

- name: "Instalando o Python 3"
  zypper:
   name: "{{ python_packages }}"
   state: present
   force: yes
  become: true
  tags:
    - ansible
    - deps


- name: "Atualizando o PIP"
  pip:
    name: pip
    state: latest
  become: true
  tags:
    - ansible
    - deps


- name: "Instalando o pacote 'Ansible' pelo PIP"
  pip:
    name: "ansible"
    state: present
  become: true
  tags:
    - ansible


- name: Criando estrutura de diretorios de /etc/ansible
  file:
    path: "/etc/ansible"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: "0775"
    recurse: yes
  become: true
  tags:
    - ansible
    - config


- name: "Copiando o arquivo de configuracao ansible.cfg para /etc/ansible/ansible.cfg"
  copy:
    src: "ansible.cfg"
    dest: /etc/ansible/ansible.cfg
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: '0644'
  become: true
  tags:
    - ansible
    - config